export const SPECIES = [
  {
    id: 'carp',
    name: 'Carp',
    image: '🐟',
    ideal: { pH: 7.2, temp: 25, turbidity: 10, oxygen: 6, ammonia: 0.05, nitrite: 0.5 },
    ranges: {
      pH: [6.8, 7.6],
      temp: [22, 28],
      turbidity: [0, 20],
      oxygen: [5, 8],
      ammonia: [0, 0.1],
      nitrite: [0, 1.0],
    },
    growthDays: 210,
    maxWeightKg: 4.2,
    description: 'Hardy, bottom-feeding freshwater fish tolerant of low oxygen but sensitive to rapid pH swings.',
  },
  {
    id: 'tilapia',
    name: 'Tilapia',
    image: '🐠',
    ideal: { pH: 7.4, temp: 28, turbidity: 15, oxygen: 5.5, ammonia: 0.1, nitrite: 0.75 },
    ranges: {
      pH: [7.0, 8.0],
      temp: [25, 31],
      turbidity: [0, 25],
      oxygen: [4.5, 7],
      ammonia: [0, 0.2],
      nitrite: [0, 1.5],
    },
    growthDays: 150,
    maxWeightKg: 1.5,
    description: 'Fast-growing warm-water species. Thrives on plant-based feed and tolerates higher ammonia.',
  },
  {
    id: 'catfish',
    name: 'Catfish',
    image: '🐱‍🐟',
    ideal: { pH: 7.0, temp: 27, turbidity: 25, oxygen: 5, ammonia: 0.15, nitrite: 0.6 },
    ranges: {
      pH: [6.5, 7.6],
      temp: [24, 30],
      turbidity: [0, 40],
      oxygen: [4, 6.5],
      ammonia: [0, 0.3],
      nitrite: [0, 1.2],
    },
    growthDays: 180,
    maxWeightKg: 2.8,
    description: 'Dense-stocking champion. Sturdy and omnivorous, best suited to turbid pond conditions.',
  },
  {
    id: 'rohu',
    name: 'Rohu',
    image: '🎏',
    ideal: { pH: 7.4, temp: 27, turbidity: 18, oxygen: 6, ammonia: 0.08, nitrite: 0.4 },
    ranges: {
      pH: [7.0, 7.9],
      temp: [24, 30],
      turbidity: [0, 30],
      oxygen: [5, 8],
      ammonia: [0, 0.15],
      nitrite: [0, 0.8],
    },
    growthDays: 200,
    maxWeightKg: 3.5,
    description: 'Indian major carp feeding on plankton. Prefers clean water with rich natural feed.',
  },
]

export const DAILY_ALERTS = [
  {
    level: 'critical',
    title: 'pH dropping below safe threshold',
    detail: 'pH at 6.51. Model projects 85% probability of critical fish mortality within 48h without intervention.',
    time: '2 min ago',
  },
  {
    level: 'warning',
    title: 'Turbidity rising rapidly',
    detail: '+9 NTU in the last hour. Possible silt inflow or waste accumulation near the inlet.',
    time: '18 min ago',
  },
  {
    level: 'info',
    title: 'Feeding cycle completed',
    detail: '1.5 kg feed dispensed via scheduled routine at 09:00. Consumption rate nominal.',
    time: '1 h ago',
  },
]
